version: '2' # required to adjust maintainability checks
checks:
  fixme:
    enabled: true
  similar-code:
    enabled: false
  identical-code:
    enabled: false
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
plugins:
  fixme:
    enabled: true
